### PR TITLE
feat(container-builds): Duplicate container builds to spinnaker-community

### PR DESCRIPTION
**Pull request by ttomsu**
Step 1 moving container images to `spinnaker-community`'s GCR registry.

### CODE REVIEW

**Review by plumpy — COMMENTED** [review]
Why not just move them to artifact registry, if we're going to go through the trouble of moving them anyway?

**Comment by ttomsu** [comment]
It's that a different endpoint/URL? I've not looked into artifact registry differences much.

**Comment by plumpy** [comment]
Yeah, because (unlike GCR) you can have multiple Docker registries per project... so it's something like docker.pkg.dev/$PROJECT/$REPO

I don't know, maybe it's not really ready yet (I think it's just beta, not GA), but could you investigate it and see? I'd hate to have to do this all over again in a year or two...

**Comment by ttomsu** [comment]
So yes, AR is still in beta, and it seems while in beta, there's no overlap between the `*-docker.pkg.dev` domain and `gcr.io`. Once in GA, [there are promises for backwards compatibility with `gcr.io`](https://cloud.google.com/artifact-registry/docs/migrate-guide#overview) - not sure how that's going to work honestly. 

Since AR requires adding two additional pieces of data to every transaction (the region & repository name), I propose tackling that later once a better plan is in place (for example, all releases get pushed to us-, europe-, and asia- regional duplicates, while nightly builds only get pushed to us-, or something like that. Second example: does it make sense to split out stable releases and nightly releases into separate repos?)

I'll write any tools/scripts in such a way to keep these changes in mind in the future.

**Comment by ttomsu** [comment]
Closing this for a more comprehensive change to move to GAR

**Pull request closed without merging**
