### PR TITLE
feat(test): remove Kubernetes V1 tests

### PR DESCRIPTION
**Pull request by maggieneterval**
Since 1.20 is the last release that will include support for V1, and the 1.20 release branches have been cut, it is now safe to remove all of the V1 code. Before deleting the V1 code from each microservice, let's remove the V1 tests so they don't fail once that code is removed.

### CODE REVIEW

**Comment by maggieneterval** [comment]
(@ttomsu happy to hold this until you are done testing the Artifact registry changes, and then test off my branch before merging).

**Review by ezimanyi — APPROVED** [review]
💯 🏅 🚫 ✌️ 1️⃣

**Review by plumpy — APPROVED** [review]
Bon Voyage, tests!!

**Comment by ttomsu** [comment]
No reservations here. Merge away.

**Comment by maggieneterval** [comment]
I'm running Build_Flow against this branch now just to make sure I didn't miss anything; will merge if it passes!

**Pull request merged**
