### PR TITLE
chore(containers): ignore stderr of `gcloud container images list-tags`

### PR DESCRIPTION
**Pull request by plumpy**

### CODE REVIEW

**Comment by plumpy** [comment]
Fixes the issue mentioned in spinnaker/spinnaker#5510

**Review by duftler — APPROVED** [review]

**Comment by plumpy** [comment]
@spinnakerbot cherrypick 1.18

**Comment by plumpy** [comment]
@spinnakerbot cherrypick 1.17

**Comment by plumpy** [comment]
@spinnakerbot cherrypick 1.16

**Comment by plumpy** [comment]
@spinnakerbot cherry-pick 1.18

**Comment by plumpy** [comment]
@spinnakerbot cherry-pick 1.17

**Comment by plumpy** [comment]
@spinnakerbot cherry-pick 1.16

**Pull request merged**
