### PR TITLE
fix(kubernetes): Actually fix race condition in V2 deployment

### PR DESCRIPTION
**Pull request by ezimanyi**
The last commit added some great logic to make sure that V2 deployments are ready before we try to port-forward to them, except that it added the logic to the V1 deployer instead of the V2 deployer. Move this logic to the V2 deployer, and add a couple of log lines so it's easier to see that it's working.

### CODE REVIEW

**Comment by ezimanyi** [comment]
:man_facepalming: 
I think it was just luck that the tests passed when I ran against the earlier branch.

**Review by plumpy — APPROVED** [review]
Service :dango: is up

**Comment by maggieneterval** [comment]
Since we don't plan on ever running the tests on a V1-deployed Spinnaker again, any thoughts on me removing the V1 deployer logic now? No need to confusingly have logic for both...

**Comment by ezimanyi** [comment]
I'd say go ahead, having just experienced the downside of having the logic still there!

**Pull request merged**
